FROM python:3.10.6

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNVUFFERED 1

WORKDIR /usr/scr/STO-SHOP

COPY ./requirements.txt /usr/scr/STO_SHOP/requirements.txt
RUN pip install -r /usr/scr/STO_SHOP/requirements.txt
